name: Lint checks

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  lint:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install deps
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[checking]
        pip install flake8
    
    - name: flake8
      run: flake8 . --show-source --statistics
